//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensesManager.Exceptions.ResourcesMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VALIDATIONMSG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VALIDATIONMSG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpensesManager.Exceptions.ResourcesMessage.VALIDATIONMSG", typeof(VALIDATIONMSG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar atualizar dados.
        /// </summary>
        public static string ADDITIONALINFO_ERROR {
            get {
                return ResourceManager.GetString("ADDITIONALINFO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve ser informado o valor da movimentação.
        /// </summary>
        public static string AMOUNT_ZERO {
            get {
                return ResourceManager.GetString("AMOUNT_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A idade deve ser maior que 13 anos.
        /// </summary>
        public static string BIRTHDATE_YEARS {
            get {
                return ResourceManager.GetString("BIRTHDATE_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode ser informada uma data futura.
        /// </summary>
        public static string DATE_FUTURE {
            get {
                return ResourceManager.GetString("DATE_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da movimentação não pode estar vazia.
        /// </summary>
        public static string DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da movimentação não pode conter apenas números.
        /// </summary>
        public static string DESCRIPTION_NUMBER {
            get {
                return ResourceManager.GetString("DESCRIPTION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha ou e-mail incorretos..
        /// </summary>
        public static string EXISTING_USER {
            get {
                return ResourceManager.GetString("EXISTING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido.
        /// </summary>
        public static string INVALID_MAIL {
            get {
                return ResourceManager.GetString("INVALID_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telefone informado é inválido.
        /// </summary>
        public static string INVALID_PHONE {
            get {
                return ResourceManager.GetString("INVALID_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail do usuário não pode estar vazio.
        /// </summary>
        public static string MAIL_EMPTY {
            get {
                return ResourceManager.GetString("MAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário não pode estar vazio.
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade não pode conter apenas números.
        /// </summary>
        public static string NATIONALITY_NUMBER {
            get {
                return ResourceManager.GetString("NATIONALITY_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupação não pode conter apenas números.
        /// </summary>
        public static string OCCUPATION_NUMBER {
            get {
                return ResourceManager.GetString("OCCUPATION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha do usuário não pode estar vazio.
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da movimentação não pode estar vazio.
        /// </summary>
        public static string TITLE_EMPTY {
            get {
                return ResourceManager.GetString("TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da movimentação não pode conter apenas números.
        /// </summary>
        public static string TITLE_NUMBER {
            get {
                return ResourceManager.GetString("TITLE_NUMBER", resourceCulture);
            }
        }
    }
}
