name: CI - Develop - ExpensesManager_Functions

on:
    pull_request:
        branches:
            - develop
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Configuring .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7.0.x

            - name: Restore Packages
              run: dotnet restore ExpensesManager_Functions.sln

            - name: Compile Project
              run: dotnet build ExpensesManager_Functions.sln --configuration Release --no-restore
